-- Advanced:

-- 1.Determine the proportionate revenue generated by each type of pizza.

SELECT 
    pizza_types.category,
    ROUND(SUM(order_details.quantity * pizzas.price) / (SELECT 
                    ROUND(SUM(order_details.quantity * pizzas.price),
                                2) AS total_income
                FROM
                    order_details
                        INNER JOIN
                    pizzas ON pizzas.pizza_id = order_details.pizza_id) * 100,
            2) AS revenue
FROM
    pizza_types
        JOIN
    pizzas ON pizzas.pizza_type_id = pizza_types.pizza_type_id
        JOIN
    order_details ON order_details.pizza_id = pizzas.pizza_id
GROUP BY pizza_types.category
ORDER BY revenue DESC;

-----------------------------------------------------------------------------------------------------------------------------------------

-- 2.Evaluate the total revenue accumulated over a period of time.

select  order_date,
sum(revenue) over (order by order_date) as cum_revenue
from
(select orders.order_date,
SUM(order_details.quantity * pizzas.price) as revenue
from  order_details JOIN pizzas
on order_details.pizza_id = pizzas.pizza_id
join orders
on orders.order_id = order_details.order_id
group by orders.order_date) as sales;

-----------------------------------------------------------------------------------------------------------------------------------------

-- 3.Identify the three pizza types with the highest revenue in each pizza category.

select name,revenue from
(select category,name,revenue,
rank() over (partition by category order by revenue desc) as rn
From
(SELECT 
   pizza_types.category, pizza_types.name,
    SUM(order_details.quantity * pizzas.price) AS revenue
FROM
    pizza_types
        JOIN
    pizzas ON pizzas.pizza_type_id = pizza_types.pizza_type_id
        JOIN
    order_details ON order_details.pizza_id = pizzas.pizza_id
GROUP BY pizza_types.category,pizza_types.name) as a) as b
where rn <= 3 ;

-----------------------------------------------------------------------------------------------------------------------------------------